all:
  hosts:
    alt:
      ansible_host: 10.0.4.12
      ansible_user: root
      lan_interface: enp0s3
      wan_interface: enp0s8
      ssh_interface: enp0s9
      ansible_python_interpreter: /usr/bin/python3.9
    astra:
      ansible_host: 10.0.4.13
      ansible_user: root
      lan_interface: eth0
      wan_interface: eth1
      ssh_interface: eth2
      ansible_python_interpreter: /usr/bin/python3.7
    rtr.localdomain:
      ansible_host: 10.0.4.254
      ansible_user: root
      lan_interface: enp0s3
      wan_interface: enp0s8
      ssh_interface: enp0s9
      ansible_python_interpreter: /usr/bin/python3.11
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    network_ips:
      router: 10.0.1.254
      db: 10.0.1.2
      client: 10.0.1.3
